### ISSUE TITLE
Why are you copy-pasting avalonia code instead of just referencing it?

### ISSUE THREAD

**Issue by kekekeks** [jpobst/Modern.Forms#6]
I think that this way you are just fragmenting the ecosystem (e. g. WPF and Winforms interop just fine, I don't see why Modern.Forms shouldn't be able to interop in the same way with Avalonia). You are also missing the new features like embedded system support, hw accelerated rendering improvements and the upcoming text layout engine.

From my understanding, you just need an SkCanvas instance and input events. You can get an hardware-accelerate SKCanvas [like this](https://github.com/AvaloniaUI/Avalonia/blob/master/samples/RenderDemo/Pages/CustomSkiaPage.cs). If you absolutely need your rendering code to run on the UI thread, you can setup an UI-thread render timer.

Also, consider using the `DrawingContext` provided by Avalonia itself, since it should be sufficient for any complex UI and allows for deferred rendering.

**Comment by jpobst** [comment]
Largely I wanted to have as few dependencies as possible that users are required to ship.  Avalonia takes the opposite (but also valid) strategy of shipping lots of small assemblies.  I will admit I did not expect to pull in as much Avalonia code when I started down that path.

It also did not seem possible to only include the foundational parts of Avalonia I was interested in due to the dependency graph.  For example, `Avalonia.Win32` references `Avalonia.Controls`, `Avalonia.DesignerSupport`, and `Avalonia.Markup.Xaml`.

If this project continues I think I would likely be interested in finding ways to better share Avalonia's code.  It is a great foundation to build on.  And a text layout engine would definitely be awesome.  :)
